@startuml "PERT diagram"

skinparam backgroundColor transparent
left to right direction

scale 0.7

<style>
stateDiagram {
  arrow {
    LineColor black
  }
}
</style>

skinparam State {
  BackgroundColor #e8f5fd
  BorderColor #5FB8EC
}

skinparam defaultTextAlignment center

state "<color:darkred>A0: Priprava okolja</color>" as A0 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  2 |  0 |  2 |\n|  0 |  0 |  2 |
state "<color:darkred>A1: Analiza zahtev</color>" as A1 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  9 |  2 | 11 |\n|  0 |  2 | 11 |
state "A2: Načrt arhitekture" as A2 : <#e8f5fd,#e8f5fd>|  6 | 11 | 17 |\n| 45 | 56 | 62 |
state "<color:darkred>A3: Predlog projekta</color>" as A3 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  7 | 11 | 18 |\n|  0 | 11 | 18 |
state "B1: Mobilna aplikacija" as B1 : <#e8f5fd,#e8f5fd>| 10 | 18 | 28 |\n| 31 | 49 | 59 |
state "<color:darkred>B2: Zaledni strežnik</color>" as B2 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>| 12 | 18 | 30 |\n|  0 | 18 | 30 |
state "B3: AI integracija" as B3 : <#e8f5fd,#e8f5fd>|  9 | 18 | 27 |\n| 35 | 53 | 62 |
state "B4: Baza pravil" as B4 : <#e8f5fd,#e8f5fd>|  7 | 18 | 25 |\n| 37 | 55 | 62 |
state "B5: 1. poročilo" as B5 : <#e8f5fd,#e8f5fd>|  3 | 28 | 31 |\n| 31 | 59 | 62 |
state "<color:darkred>C1: Integracija FE-BE</color>" as C1 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  4 | 30 | 34 |\n|  0 | 30 | 34 |
state "<color:darkred>C2: Testiranje</color>" as C2 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>| 11 | 34 | 45 |\n|  0 | 34 | 45 |
state "C3: 2. poročilo" as C3 : <#e8f5fd,#e8f5fd>|  2 | 34 | 36 |\n| 26 | 60 | 62 |
state "<color:darkred>D1: Upor. testiranje</color>" as D1 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  5 | 45 | 50 |\n|  0 | 45 | 50 |
state "<color:darkred>D2: Optimizacija</color>" as D2 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  5 | 50 | 55 |\n|  0 | 50 | 55 |
state "D3: Dokumentacija" as D3 : <#e8f5fd,#e8f5fd>|  5 | 50 | 55 |\n|  7 | 57 | 62 |
state "<color:darkred>D4: Končni produkt</color>" as D4 #ffe6e6;line:darkred : <#ffe6e6,#ffe6e6>|  7 | 55 | 62 |\n|  0 | 55 | 62 |

[*] -[#darkred,bold]-> A0
A0 -[#darkred,bold]-> A1
A1 --> A2
A1 -[#darkred,bold]-> A3
A3 -[#darkred,bold]-> B2
A3 --> B1
A3 --> B3
A3 --> B4
B1 --> B5
B2 -[#darkred,bold]-> C1
C1 -[#darkred,bold]-> C2
C1 --> C3
C2 -[#darkred,bold]-> D1
D1 -[#darkred,bold]-> D2
D1 --> D3
D2 -[#darkred,bold]-> D4
D4 -[#darkred,bold]-> [*]

@enduml
